apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: demo
type: Opaque
stringData:
  # stringData lets us write the plain value aand K8s base64 encodes it automatically
  MongoDbSettings__ConnectionString: "mongodb://admin:devpassword@mongodb-service.demo.svc.cluster.local:27017/demodb?authSource=admin"