apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: demo
  labels:
    app: demo-ui
spec:
  selector:
    app: demo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP